language: node_js
node_js:
  - lts/*
install:
  - npm install  
script:
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: public # 项目打包后生成的文件的目录
  github-token: $GH_TOKEN # 这里这个变量是Github Token
  keep-history: true
  on:
    branch: master # 项目源码所在的分支